sweetsProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from sweetsbyhaydee import views

urlpatterns = [
    path('', views.index, name= 'index'),
    path('sweetsbyhaydee/', include('sweetsbyhaydee.urls')),
    path('admin/', admin.site.urls),
]

sweetsbyhaydee/urls.py
from django.conf.urls import url
from . import views

#TEMPLATE TAGGING
app_name = 'sweetsbyhaydee'

urlpatterns = [
    url(r'^users/$', views.users, name='users'),
    url(r'^quem_sou/$', views.quem_sou, name='quem_sou'),
]

sweetsbyhaydee/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254,unique=True)
    

sweetsbyhaydee/forms.py
from django import forms
from sweetsbyhaydee.models import User

class NewUserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = '__all__'

sweetsbyhaydee/views.py
from django.shortcuts import render
#from django.http import HttpResponse
#from sweetsbyhaydee.models import User
from sweetsbyhaydee.forms import NewUserForm
# Create your views here.

def index(request):
    return render(request, 'sweetsbyhaydee/index.html')

def quem_sou(request):
    return render(request, 'sweetsbyhaydee/quem_sou.html')

def base(request):
    return render(request, 'sweetsbyhaydee/base.html')

def users(request):
    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')
    return render(request, 'sweetsbyhaydee/users.html', {'form':form})

templates/sweetsbyhaydee/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="conteiner">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">BRAND</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a class="navbar-link" href="{% url 'sweetsbyhaydee:users' %}">users</a> </li>
          <li> <a class="navbar-link" href="{% url 'sweetsbyhaydee:quem_sou' %}">Quem Sou</a> </li>
        </ul>
      </div>
    </nav>
    <div class="conteiner">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

templates/sweetsbyhaydee/index.html
<!DOCTYPE html>
{% extends "sweetsbyhaydee/base.html" %}
  {% block body_block %}
    <h1>Welcome!</h1>
  {% endblock %}

templates/sweetsbyhaydee/quem_sou.html
<!DOCTYPE html>
{% extends "sweetsbyhaydee/base.html"%}
  {% block body_block %}
    <h1>Quem Sou</h1>
  {% endblock %}

templates/sweetsbyhaydee/users.html
<!DOCTYPE html>
{% extends "sweetsbyhaydee/base.html" %}
  {% block body_block %}
        <h1>Please sign up here!</h1>
        <form method="POST">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="Sumit">
    {% endblock %}